[package]
name = "snippet"
version = "0.1.4-alpha.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
itoa = "0.3.4"
one = { path = "one" }
two = { path = "two" }
three = { git = "file:///build/three", rev = "297eafaa76d42b318ae11435ab910e725a92fce0" }
